name: Run Daily Claim Ninja Heroes Script


on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '15 17 * * *' # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6' # Using Python 3.12.6

    - name: Install dependencies in 'game' folder
      run: |
        cd game
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements file found"

    - name: Installing package list
      run: apt list --installed    
    - name: Removing previous chrome instances on runner 
      run: sudo apt purge google-chrome-stable  
      
      # Need to fetch reqs if needed
    - name: Installing all necessary packages
      run: pip install chromedriver-autoinstaller pyvirtualdisplay
    - name: Install xvfb
      run: sudo apt-get install xvfb


    - name: Run Python script
      env: # Pass GitHub secrets to the script
        MAIN_MAIL: ${{ secrets.MAIN_MAIL }}
        MAIL_PASS_NH: ${{ secrets.MAIL_PASS_NH }}
      run: |
        export DISPLAY=:99
        Xvfb :99 &  # Start Xvfb
        python game/ninja-heroes-claim-daily.py
    
    - name: 'Debug: List all files in game directory'
      run: ls -la game/  

    - name: Upload logs as artifact
      if: always() # Upload logs even if the script fails
      uses: actions/upload-artifact@v3
      with:
        name: daily-claim-log
        path: game/daily_claim.log